# Stage 1: Build React App
FROM node:14 as build-react-app

WORKDIR /app/frontend

COPY rhombus-ai-frontend/package.json rhombus-ai-frontend/package-lock.json ./
RUN npm install

COPY rhombus-ai-frontend ./
RUN npm run build

# Stage 2: Serve React App with nginx
FROM nginx:alpine

COPY --from=build-react-app /app/frontend/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]
